package org.codelabor.system.certification.name.services;

public enum NameCertificationStatus {
	CERTIFICATED, NOT_CERTIFICATED, NO_DATA, NOT_ADULT, INCORRECT_RESISTRATION_NUMBER, INCORRECT_DATA,

	INCORRECT_SITE_CODE, INCORRECT_SITE_PASSWORD, EXPIRED_SITE_CODE, PROVIDER_SYSTEM_ERROR, PROVIDER_SERVICE_ERROR, DECODING_SYSTEM_ERROR, DECODING_SERVICE_ERROR, INCORRECT_ENCRYPTION_DATA, ENCRYPTION_ERROR, ILLEGAL_RESISTRATION_NUMBER, CONNECTION_ERROR, URL_NOT_FOUND, UNKNOWN_ERROR, MALFORMED_URL_EXCEPTION, NO_ROUTE_TO_HOST_EXCEPTION

}
