CREATE TABLE ACL_SID( ID int NOT NULL,
PRINCIPAL number(1) NOT NULL,
SID VARCHAR(100) NOT NULL,
CONSTRAINT ACL_SID_PK PRIMARY KEY (ID));

CREATE TABLE ACL_CLASS( ID int NOT NULL,
CLASS VARCHAR(100) NOT NULL,
CONSTRAINT ACL_CLASS_PK PRIMARY KEY (ID),
CONSTRAINT ACL_CLASS_UNIQUE_CLASS UNIQUE(CLASS));
 
CREATE TABLE ACL_OBJECT_IDENTITY( ID int NOT NULL,
OBJECT_ID_CLASS INT NOT NULL,
OBJECT_ID_IDENTITY INT NOT NULL,
PARENT_OBJECT INT,
OWNER_SID INT,
ENTRIES_INHERITING number(1) NOT NULL,
CONSTRAINT ACL_O_I_PK PRIMARY KEY (ID),
CONSTRAINT ACL_O_I_UNIQUE_CLASS_OID UNIQUE(OBJECT_ID_CLASS,OBJECT_ID_IDENTITY),
CONSTRAINT FK_AOI_PARENT_OBJECT FOREIGN KEY(PARENT_OBJECT) REFERENCES ACL_OBJECT_IDENTITY(ID),
CONSTRAINT FK_AOI_ACL_CLASS FOREIGN KEY(OBJECT_ID_CLASS) REFERENCES ACL_CLASS(ID),
CONSTRAINT FK_AOI_ACL_SID FOREIGN KEY(OWNER_SID) REFERENCES ACL_SID(ID));

CREATE TABLE ACL_ENTRY( ID int NOT NULL PRIMARY KEY,
ACL_OBJECT_IDENTITY int NOT NULL,
ACE_ORDER INT NOT NULL,
SID int NOT NULL,
MASK INTEGER NOT NULL,
GRANTING number(1) NOT NULL,
AUDIT_SUCCESS number(1) NOT NULL,
AUDIT_FAILURE number(1) NOT NULL,
CONSTRAINT ACL_ENTRY_UNIQUE_OID_ORDER UNIQUE(ACL_OBJECT_IDENTITY,ACE_ORDER),
CONSTRAINT FK_ACL_ENTRY_AOI FOREIGN KEY(ACL_OBJECT_IDENTITY) REFERENCES ACL_OBJECT_IDENTITY(ID),
CONSTRAINT FK_ACL_ENTRY_ACL_SID FOREIGN KEY(SID) REFERENCES ACL_SID(ID));

CREATE SEQUENCE ACL_SID_SEQUENCE;

CREATE OR REPLACE TRIGGER ACL_SID_ID
BEFORE INSERT ON ACL_SID
FOR EACH ROW
BEGIN
SELECT ACL_SID_SEQUENCE.NEXTVAL INTO :new.id FROM dual;
END;

CREATE SEQUENCE ACL_CLASS_SEQUENCE;

CREATE OR REPLACE TRIGGER ACL_CLASS_ID
BEFORE INSERT ON ACL_SID
FOR EACH ROW
BEGIN
SELECT ACL_CLASS_SEQUENCE.NEXTVAL INTO :new.id FROM dual;
END;