INSERT INTO GROUP_AUTHORITIES (GROUP_ID, AUTHORITY) VALUES (1, 'ROLE_ADMINISTRATOR');
INSERT INTO GROUP_AUTHORITIES (GROUP_ID, AUTHORITY) VALUES (2, 'ROLE_MANAGER');
INSERT INTO GROUP_AUTHORITIES (GROUP_ID, AUTHORITY) VALUES (3, 'ROLE_DEVELOPER');
INSERT INTO GROUP_AUTHORITIES (GROUP_ID, AUTHORITY) VALUES (4, 'ROLE_STUDENT');
INSERT INTO GROUP_AUTHORITIES (GROUP_ID, AUTHORITY) VALUES (5, 'ROLE_TEACHER');
INSERT INTO GROUP_AUTHORITIES (GROUP_ID, AUTHORITY) VALUES (6, 'ROLE_PARENTS');
INSERT INTO GROUP_AUTHORITIES (GROUP_ID, AUTHORITY) VALUES (7, 'ROLE_STAFF');