INSERT INTO GROUPS (ID, GROUP_NAME) VALUES (1, 'Administrator');
INSERT INTO GROUPS (ID, GROUP_NAME) VALUES (2, 'Manager');
INSERT INTO GROUPS (ID, GROUP_NAME) VALUES (3, 'Developer');
INSERT INTO GROUPS (ID, GROUP_NAME) VALUES (4, 'Student');
INSERT INTO GROUPS (ID, GROUP_NAME) VALUES (5, 'Teacher');
INSERT INTO GROUPS (ID, GROUP_NAME) VALUES (6, 'Parents');
INSERT INTO GROUPS (ID, GROUP_NAME) VALUES (7, 'Staff');

