DROP TABLE SIGN CASCADE CONSTRAINTS;

CREATE TABLE SIGN
(
	ID					NUMBER(27) PRIMARY KEY NOT NULL,
	SUBJECT				VARCHAR2(512),
	SIGNED_MESSAGE		CLOB,
	CERT_TYPE			VARCHAR2(512),
	CERT_PEM			CLOB,
	SIGNED_DATE			TIMESTAMP
);


