DROP TABLE SIGN CASCADE CONSTRAINTS;

CREATE TABLE SIGN
(
	ID					NUMBER(27) PRIMARY KEY NOT NULL,
	SUBJECT				VARCHAR2(512),
	SIGNED_MESSAGE		VARCHAR2(512),
	CERT_TYPE			VARCHAR2(512),
	CERT_PEM			VARCHAR2(512),
	SIGNED_DATE			TIMESTAMP
);


