DROP TABLE ACCESS_LOG;

CREATE TABLE ACCESS_LOG (
	SEQ			DEC(16, 0) PRIMARY KEY NOT NULL,
	USER_ID		VARCHAR(32),
	RESOURCE_ID	VARCHAR(32),
	MESSAGE		VARCHAR(1024),
	IP_ADDRESS	VARCHAR(16),
	TIMESTAMP	TIMESTAMP DEFAULT CURRENT TIMESTAMP
);