DROP TABLE ACCESS_LOG;

CREATE TABLE ACCESS_LOG (
	SEQ			DEC(16, 0) PRIMARY KEY NOT NULL,
	USERNAME	VARCHAR(32),
	TARGET		VARCHAR(32),
	EVENT		VARCHAR(1024),
	IP_ADDRESS	VARCHAR(16),
	TIMESTAMP	TIMESTAMP DEFAULT CURRENT TIMESTAMP
);