CREATE TABLE ACL_SID
(
	ID NUMBER(20,0) NOT NULL PRIMARY KEY CHECK(ID >= 0),
	PRINCIPAL NUMBER(3,0) NOT NULL,
	SID VARCHAR2(100) NOT NULL,
	UNIQUE(SID,PRINCIPAL)
);

/*
DROP SEQUENCE ACL_SID_ID;
CREATE SEQUENCE ACL_SID_ID INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER ACL_SID_ID
BEFORE INSERT ON ACL_SID
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
WHEN(NEW.ID IS NULL)
BEGIN
	SELECT ACL_SID_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
*/

CREATE TABLE ACL_CLASS
(
	ID NUMBER(20,0) NOT NULL PRIMARY KEY CHECK(ID >= 0),
	CLASS VARCHAR2(100) UNIQUE NOT NULL
);

/*
DROP SEQUENCE ACL_CLASS_ID;
CREATE SEQUENCE ACL_CLASS_ID INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER ACL_CLASS_ID
BEFORE INSERT ON ACL_CLASS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
WHEN(NEW.ID IS NULL)
BEGIN
	SELECT ACL_CLASS_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
*/

CREATE TABLE ACL_OBJECT_IDENTITY
(
	ID NUMBER(20,0) NOT NULL PRIMARY KEY CHECK(ID >= 0),
	OBJECT_ID_CLASS NUMBER(20,0) NOT NULL CHECK(OBJECT_ID_CLASS >= 0),
	OBJECT_ID_IDENTITY NUMBER(20,0) NOT NULL CHECK(OBJECT_ID_IDENTITY >= 0),
	PARENT_OBJECT NUMBER(20,0)	CHECK(PARENT_OBJECT >= 0),
	OWNER_SID NUMBER(20,0)	CHECK(OWNER_SID >= 0),
	ENTRIES_INHERITING NUMBER(3,0) NOT NULL,
	UNIQUE(OBJECT_ID_CLASS,OBJECT_ID_IDENTITY),
	FOREIGN KEY(OBJECT_ID_CLASS) REFERENCES ACL_CLASS(ID),
	FOREIGN KEY(PARENT_OBJECT) REFERENCES ACL_OBJECT_IDENTITY(ID),
	FOREIGN KEY(OWNER_SID) REFERENCES ACL_SID(ID)
);

/*
DROP SEQUENCE ACL_OBJECT_IDENTITY_ID;
CREATE SEQUENCE ACL_OBJECT_IDENTITY_ID INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER ACL_OBJECT_IDENTITY_ID
BEFORE INSERT ON ACL_OBJECT_IDENTITY
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
WHEN(NEW.ID IS NULL)
BEGIN
	SELECT ACL_OBJECT_IDENTITY_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
*/

CREATE TABLE ACL_ENTRY
(
	ID NUMBER(20,0) NOT NULL PRIMARY KEY CHECK(ID >= 0),
	ACL_OBJECT_IDENTITY NUMBER(20,0) NOT NULL CHECK(ACL_OBJECT_IDENTITY >= 0),
	ACE_ORDER NUMBER(10,0) NOT NULL CHECK(ACE_ORDER >= 0),
	SID NUMBER(20,0) NOT NULL CHECK(SID >= 0),
	MASK NUMBER(10,0) NOT NULL,
	GRANTING NUMBER(3,0) NOT NULL,
	AUDIT_SUCCESS NUMBER(3,0) NOT NULL,
	AUDIT_FAILURE NUMBER(3,0) NOT NULL,
	UNIQUE(ACL_OBJECT_IDENTITY,ACE_ORDER),
	FOREIGN KEY(ACL_OBJECT_IDENTITY)
	REFERENCES ACL_OBJECT_IDENTITY(ID),
	FOREIGN KEY(SID) REFERENCES ACL_SID(ID)
);

/*
DROP SEQUENCE ACL_ENTRY_ID;
CREATE SEQUENCE ACL_ENTRY_ID INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER ACL_ENTRY_ID
BEFORE INSERT ON ACL_ENTRY
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
WHEN(NEW.ID IS NULL)
BEGIN
	SELECT ACL_ENTRY_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
*/