CREATE TABLE GROUPS
(
	ID NUMBER(20,0) NOT NULL PRIMARY KEY CHECK(ID >= 0),
	GROUP_NAME VARCHAR2(50) NOT NULL
);

/*
DROP SEQUENCE GROUPS_ID;
CREATE SEQUENCE GROUPS_ID INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER GROUPS_ID
BEFORE INSERT ON GROUPS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
WHEN(NEW.ID IS NULL)
BEGIN
	SELECT GROUPS_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
*/

CREATE TABLE GROUP_AUTHORITIES
(
	GROUP_ID NUMBER(20,0) NOT NULL CHECK(GROUP_ID >= 0),
	AUTHORITY VARCHAR2(50) NOT NULL,
	FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(ID)
);

CREATE TABLE GROUP_MEMBERS
(
	ID NUMBER(20,0) NOT NULL PRIMARY KEY CHECK(ID >= 0),
	USERNAME VARCHAR2(50) NOT NULL,
	GROUP_ID NUMBER(20,0) NOT NULL CHECK(GROUP_ID >= 0),
	FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(ID)
);

/*
DROP SEQUENCE GROUP_MEMBERS_ID;
CREATE SEQUENCE GROUP_MEMBERS_ID INCREMENT BY 1 START WITH 1;

CREATE OR REPLACE TRIGGER GROUP_MEMBERS_ID
BEFORE INSERT ON GROUP_MEMBERS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
WHEN(NEW.ID IS NULL)
BEGIN
	SELECT GROUP_MEMBERS_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
*/