CREATE TABLE USERS
(
	USERNAME VARCHAR2(50) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR2(50) NOT NULL,
	ENABLED NUMBER(1,0) NOT NULL
);

CREATE TABLE AUTHORITIES
(
	USERNAME VARCHAR2(50) NOT NULL,
	AUTHORITY VARCHAR2(50) NOT NULL,
	FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME),
	UNIQUE(USERNAME,AUTHORITY)
);