INSERT INTO USERS_AUTHORITIES_MAP ( USERNAME, AUTHORITY
) VALUES (
'admin', 'ROLE_ADMIN');
INSERT INTO USERS_AUTHORITIES_MAP ( USERNAME, AUTHORITY
) VALUES (
'bomber', 'ROLE_USER');
INSERT INTO USERS_AUTHORITIES_MAP ( USERNAME, AUTHORITY
) VALUES (
'user1', 'ROLE_USER');
INSERT INTO USERS_AUTHORITIES_MAP ( USERNAME, AUTHORITY
) VALUES (
'user2', 'ROLE_USER');
INSERT INTO USERS_AUTHORITIES_MAP ( USERNAME, AUTHORITY
) VALUES (
'tester1', 'ROLE_TESTER');
INSERT INTO USERS_AUTHORITIES_MAP ( USERNAME, AUTHORITY
) VALUES (
'tester2', 'ROLE_TESTER');
COMMIT;
