DROP TABLE ADDRESSBOOK_OTHER PURGE;

CREATE TABLE ADDRESSBOOK_OTHER (
	OTHER_ID VARCHAR2(10) NOT NULL,
	CUSTOM1 VARCHAR2(64),
	CUSTOM2 VARCHAR2(64),
	CUSTOM3 VARCHAR2(64),
	CUSTOM4 VARCHAR2(64),
	NOTES VARCHAR2(64)
);
