DROP TABLE ADDRESSBOOK_PRIVATE PURGE;

CREATE TABLE ADDRESSBOOK_PRIVATE (
	PRIVATE_ID VARCHAR2(10) NOT NULL,
	ADDRESS VARCHAR2(64),
	CITY VARCHAR2(32),
	STATE VARCHAR2(8),
	ZIP VARCHAR2(64),
	COUNTRY VARCHAR2(16),
	WEBPAGE VARCHAR2(128),
	BIRTHDAY DATE
);
