DROP TABLE ADDRESSBOOK_CONTACT PURGE;

CREATE TABLE ADDRESSBOOK_CONTACT (
	CONTACT_ID VARCHAR2(10) NOT NULL,
	FIRST_NAME VARCHAR2(32),
	LAST_NAME VARCHAR2(32),
	DISPLAY VARCHAR2(64),
	NICK_NAME VARCHAR2(32),
	EMAIL VARCHAR2(64),
	ADDITIONAL_EMAIL VARCHAR2(64),
	SCREEN_NAME VARCHAR2(32),
	WORK_PHONE_NUMBER VARCHAR2(32),
	HOME_PHONE_NUMBER VARCHAR2(32),
	MOBILE_PHONE_NUMBER VARCHAR2(32),
	PAGER_NUMBER VARCHAR2(32),
	FAX_NUMBER VARCHAR2(32)
);
