INSERT INTO CRUD ( ID, FIELD1, FIELD2) VALUES (0, 'VALUE0', 'VALUE0');
INSERT INTO CRUD ( ID, FIELD1, FIELD2) VALUES (1, 'VALUE1', 'VALUE1');
INSERT INTO CRUD ( ID, FIELD1, FIELD2) VALUES (2, 'VALUE2', 'VALUE2');
INSERT INTO CRUD ( ID, FIELD1, FIELD2) VALUES (3, 'VALUE3', 'VALUE3');
INSERT INTO CRUD ( ID, FIELD1, FIELD2) VALUES (4, 'VALUE4', 'VALUE4');
INSERT INTO CRUD ( ID, FIELD1, FIELD2) VALUES (5, 'VALUE5', 'VALUE5');


