CREATE TABLE CERTIFICATES_USERS_MAP (
	DN	VARCHAR(256),
	USERNAME	VARCHAR(32),
	CONSTRAINT FK_DN2 FOREIGN KEY (DN) REFERENCES CERTIFICATES (DN) ON DELETE CASCADE,
	CONSTRAINT FK_USERNAME2 FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME) ON DELETE CASCADE
);