INSERT INTO AUTHORITIES ( AUTHORITY, DESCRIPTION
) VALUES (
'ROLE_ADMIN', NULL);
INSERT INTO AUTHORITIES ( AUTHORITY, DESCRIPTION
) VALUES (
'ROLE_USER', NULL);
INSERT INTO AUTHORITIES ( AUTHORITY, DESCRIPTION
) VALUES (
'ROLE_TESTER', NULL);

INSERT INTO AUTHORITIES ( AUTHORITY, DESCRIPTION
) VALUES (
'IS_AUTHENTICATED_FULLY', NULL);
INSERT INTO AUTHORITIES ( AUTHORITY, DESCRIPTION
) VALUES (
'IS_AUTHENTICATED_REMEMBERED', NULL);
INSERT INTO AUTHORITIES ( AUTHORITY, DESCRIPTION
) VALUES (
'IS_AUTHENTICATED_ANONYMOUSLY', NULL);
COMMIT;

