INSERT INTO RESOURCES (RESOURCE_ID, RESOURCE_NAME, RESOURCE_PATTERN, DESCRIPTION, RESOURCE_TYPE, SORT_ORDER) VALUES ('WEB-000001', 'TEST_RESOURCE_1', '/INDEX.*', '', 'URL', 10);
INSERT INTO RESOURCES (RESOURCE_ID, RESOURCE_NAME, RESOURCE_PATTERN, DESCRIPTION, RESOURCE_TYPE, SORT_ORDER) VALUES ('WEB-000002', 'TEST_RESOURCE_2', '/XECUREOBJECT/**', '', 'URL', 100);
INSERT INTO RESOURCES (RESOURCE_ID, RESOURCE_NAME, RESOURCE_PATTERN, DESCRIPTION, RESOURCE_TYPE, SORT_ORDER) VALUES ('WEB-000003', 'TEST_RESOURCE_3', '/SYSTEM/LOGIN/HOME.DO*', '', 'URL', 1000);
INSERT INTO RESOURCES (RESOURCE_ID, RESOURCE_NAME, RESOURCE_PATTERN, DESCRIPTION, RESOURCE_TYPE, SORT_ORDER) VALUES ('WEB-000004', 'TEST_RESOURCE_4', '/SYSTEM/LOGIN/XECURE/LOGIN.DO*', '', 'URL', 1100);
INSERT INTO RESOURCES (RESOURCE_ID, RESOURCE_NAME, RESOURCE_PATTERN, DESCRIPTION, RESOURCE_TYPE, SORT_ORDER) VALUES ('WEB-000005', 'TEST_RESOURCE_5', '/SERVLET/SYSTEM/SNIFFERSERVLET*', '', 'URL', 2000);
INSERT INTO RESOURCES (RESOURCE_ID, RESOURCE_NAME, RESOURCE_PATTERN, DESCRIPTION, RESOURCE_TYPE, SORT_ORDER) VALUES ('WEB-000006', 'TEST_RESOURCE_6', '/SERVLET/SYSTEM/SNIFFER/XECURESNIFFERSERVLET*', '', 'URL', 2100);
INSERT INTO RESOURCES (RESOURCE_ID, RESOURCE_NAME, RESOURCE_PATTERN, DESCRIPTION, RESOURCE_TYPE, SORT_ORDER) VALUES ('WEB-000007', 'TEST_RESOURCE_7', '/SERVLET/SYSTEM/FILE/XECUREFILEUPLOADSERVLET*', '', 'URL', 3000);
INSERT INTO RESOURCES (RESOURCE_ID, RESOURCE_NAME, RESOURCE_PATTERN, DESCRIPTION, RESOURCE_TYPE, SORT_ORDER) VALUES ('WEB-000008', 'TEST_RESOURCE_8', '/SYSTEM/ERROR/**', '', 'URL', 10000);
INSERT INTO RESOURCES (RESOURCE_ID, RESOURCE_NAME, RESOURCE_PATTERN, DESCRIPTION, RESOURCE_TYPE, SORT_ORDER) VALUES ('WEB-000009', 'TEST_RESOURCE_9', '/SYSTEM/ADMINISTRATION/**', '', 'URL', 20000);
INSERT INTO RESOURCES (RESOURCE_ID, RESOURCE_NAME, RESOURCE_PATTERN, DESCRIPTION, RESOURCE_TYPE, SORT_ORDER) VALUES ('WEB-000010', 'TEST_RESOURCE_10', '/SYSTEM/PREFERENCES/**', '', 'URL', 30000);
INSERT INTO RESOURCES (RESOURCE_ID, RESOURCE_NAME, RESOURCE_PATTERN, DESCRIPTION, RESOURCE_TYPE, SORT_ORDER) VALUES ('WEB-000011', 'TEST_RESOURCE_11', '/**', '', 'URL', 99999);

INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000001', 'IS_AUTHENTICATED_ANONYMOUSLY');
INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000002', 'IS_AUTHENTICATED_ANONYMOUSLY');
INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000003', 'IS_AUTHENTICATED_ANONYMOUSLY');
INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000004', 'IS_AUTHENTICATED_ANONYMOUSLY');
INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000005', 'IS_AUTHENTICATED_ANONYMOUSLY');
INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000006', 'IS_AUTHENTICATED_ANONYMOUSLY');
INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000007', 'IS_AUTHENTICATED_ANONYMOUSLY');
INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000008', 'IS_AUTHENTICATED_ANONYMOUSLY');
INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000009', 'ROLE_ADMIN');
INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000010', 'ROLE_ADMIN');
INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000010', 'ROLE_USER');
INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000011', 'ROLE_ADMIN');
INSERT INTO RESOURCES_AUTHORITIES_MAP(RESOURCE_ID, AUTHORITY) VALUES ('WEB-000011', 'ROLE_USER');

COMMIT;