DROP TABLE ADDRESSBOOK_WORK PURGE;

CREATE TABLE ADDRESSBOOK_WORK (
	WORK_ID VARCHAR2(10) NOT NULL,
	TITLE VARCHAR2(64),
	DEPARTMENT VARCHAR2(64),
	ORGANIZATION VARCHAR2(64),
	ADDRESS VARCHAR2(64),
	CITY VARCHAR2(32),
	STATE VARCHAR2(8),
	ZIP VARCHAR2(64),
	COUNTRY VARCHAR2(16),
	WEBPAGE VARCHAR2(128)
);
