INSERT INTO EXAMPLE_ROLE ( ROLE_ID, DESCRIPTION
) VALUES ( 
'ADMIN', NULL); 
INSERT INTO EXAMPLE_ROLE ( ROLE_ID, DESCRIPTION
) VALUES ( 
'USER', NULL);
INSERT INTO EXAMPLE_ROLE ( ROLE_ID, DESCRIPTION
) VALUES ( 
'GUEST', NULL);
COMMIT;

