CREATE TABLE USER_AUTHORITY_MAP (
	USERNAME	VARCHAR(32),
	AUTHORITY	VARCHAR(32),
	CONSTRAINT FK_USERNAME FOREIGN KEY (USERNAME) REFERENCES USER (USERNAME) ON DELETE CASCADE,
	CONSTRAINT FK_AUTHORITY FOREIGN KEY (AUTHORITY) REFERENCES AUTHORITY (AUTHORITY) ON DELETE CASCADE
);