CREATE TABLE SYSTEM_USER_AUTHORITY_MAP (
	USERNAME	VARCHAR(32),
	AUTHORITY	VARCHAR(32),
	CONSTRAINT FK_USERNAME FOREIGN KEY (USERNAME) REFERENCES SYSTEM_USER (USERNAME) ON DELETE CASCADE,
	CONSTRAINT FK_AUTHORITY FOREIGN KEY (AUTHORITY) REFERENCES SYSTEM_AUTHORITY (AUTHORITY) ON DELETE CASCADE
);