INSERT INTO AUTHORITIES ( AUTHORITY, DESCRIPTION
) VALUES ( 
'ADMIN', NULL); 
INSERT INTO AUTHORITIES ( AUTHORITY, DESCRIPTION
) VALUES ( 
'USER', NULL);
INSERT INTO AUTHORITIES ( AUTHORITY, DESCRIPTION
) VALUES ( 
'TESTER', NULL);
COMMIT;

