INSERT INTO AUTHORITIES ( AUTHORITY, DESCRIPTION
) VALUES ( 
'ROLE_ADMIN', NULL); 
INSERT INTO AUTHORITIES ( AUTHORITY, DESCRIPTION
) VALUES ( 
'ROLE_USER', NULL);
INSERT INTO AUTHORITIES ( AUTHORITY, DESCRIPTION
) VALUES ( 
'ROLE_TESTER', NULL);
COMMIT;

