INSERT INTO SYSTEM_USER_AUTHORITY_MAP ( USERNAME, AUTHORITY
) VALUES ( 
'admin', 'ROLE_ADMIN'); 
INSERT INTO SYSTEM_USER_AUTHORITY_MAP ( USERNAME, AUTHORITY
) VALUES ( 
'bomber', 'ROLE_USER');
COMMIT;
