INSERT INTO USERS_AUTHORITIES_MAP ( USERNAME, AUTHORITY
) VALUES ( 
'admin', 'ADMIN'); 
INSERT INTO USERS_AUTHORITIES_MAP ( USERNAME, AUTHORITY
) VALUES ( 
'bomber', 'USER');
INSERT INTO USERS_AUTHORITIES_MAP ( USERNAME, AUTHORITY
) VALUES ( 
'tester1', 'TESTER');
INSERT INTO USERS_AUTHORITIES_MAP ( USERNAME, AUTHORITY
) VALUES ( 
'tester2', 'TESTER');
COMMIT;
