DROP TABLE ACCESS_LOG PURGE;

CREATE TABLE ACCESS_LOG (
	SEQ			NUMBER(16, 0),
	USERNAME	VARCHAR2(32),
	TARGET		VARCHAR2(32),
	EVENT		VARCHAR2(1024),
	IP_ADDRESS	VARCHAR2(16),
	TIMESTAMP	DATE DEFAULT SYSDATE,
	PRIMARY KEY ("SEQ") ENABLE
);