CREATE TABLE DEPT (
		DEPTNO NUMBER(2 , 0) NOT NULL,
		DNAME VARCHAR2(14),
		LOC VARCHAR2(13)
	);

CREATE UNIQUE INDEX PK_DEPT ON DEPT (DEPTNO ASC);

ALTER TABLE DEPT ADD CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO);