CREATE TABLE USERS_AUTHORITIES_MAP (
	USERNAME	VARCHAR(32),
	AUTHORITY	VARCHAR(32),
	CONSTRAINT FK_USERNAME FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME) ON DELETE CASCADE,
	CONSTRAINT FK_AUTHORITY FOREIGN KEY (AUTHORITY) REFERENCES AUTHORITIES (AUTHORITY) ON DELETE CASCADE
);