CREATE TABLE IF NOT EXISTS EMP (
		EMPNO SMALLINT NOT NULL,
		ENAME VARCHAR(10),
		JOB VARCHAR(9),
		MGR SMALLINT,
		HIREDATE DATETIME,
		SAL DECIMAL(7 , 2),
		COMM DECIMAL(7 , 2),
		DEPTNO TINYINT
	);
	
CREATE UNIQUE INDEX PK_EMP ON EMP (EMPNO ASC);

ALTER TABLE EMP ADD CONSTRAINT PK_EMP PRIMARY KEY (EMPNO);

ALTER TABLE EMP ADD CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO)
	REFERENCES DEPT (DEPTNO)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;