CREATE TABLE IF NOT EXISTS DEPT (
		DEPTNO TINYINT NOT NULL,
		DNAME VARCHAR(14),
		LOC VARCHAR(13)
	);
	
CREATE UNIQUE INDEX PK_DEPT ON DEPT (DEPTNO ASC);

ALTER TABLE DEPT ADD CONSTRAINT PK_DEPT PRIMARY KEY (DEPTNO);	