INSERT INTO EXAMPLE_DEPT (DEPTNO, DNAME, LOC) VALUES (10,'ACCOUNTING','NEW YORK');
INSERT INTO EXAMPLE_DEPT (DEPTNO, DNAME, LOC) VALUES (20,'RESEARCH','DALLAS');
INSERT INTO EXAMPLE_DEPT (DEPTNO, DNAME, LOC) VALUES (30,'SALES','CHICAGO');
INSERT INTO EXAMPLE_DEPT (DEPTNO, DNAME, LOC) VALUES (40,'OPERATIONS','BOSTON');