INSERT INTO EXAMPLE_ROLE ( ROLE_ID, DESCRIPTION
) VALUES ( 
'ROLE_ADMIN', NULL); 
INSERT INTO EXAMPLE_ROLE ( ROLE_ID, DESCRIPTION
) VALUES ( 
'ROLE_USER', NULL);
INSERT INTO EXAMPLE_ROLE ( ROLE_ID, DESCRIPTION
) VALUES ( 
'ROLE_GUEST', NULL);
COMMIT;

