DROP TABLE LOGIN;

CREATE TABLE LOGIN (
	SESSION_ID	VARCHAR(64) PRIMARY KEY NOT NULL,
	USER_ID		VARCHAR(32),
	IP_ADDRESS	VARCHAR(16),
	LOGIN_TIMESTAMP	TIMESTAMP DEFAULT CURRENT TIMESTAMP,
	LOGOUT_TIMESTAMP TIMESTAMP	
);