INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('admin', 'ROLE_ADMINISTRATOR'); 
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('dev1', 'ROLE_DEVELOPER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('dev2', 'ROLE_DEVELOPER');